---
title: "Abacus - Part 3"
author: "Bernat Bramon & Fernando Cagua"
date: "December 15, 2017"
---
  
Let's get into making the most out of the cluster...

# Parallel jobs

flag y concepto

##

What is a parallel job?

##

Running three times the same job would look something like this...

```{bash, eval = F}
qsub -cwd -S /bin/bash script.sh
qsub -cwd -S /bin/bash script.sh
qsub -cwd -S /bin/bash script.sh
```

##

There is a more efficient way of doing this...

```{bash, eval = F}
qsub -t 1-3 -cwd -S /bin/bash script.sh
```

##

What if we need to slightly change the script for every iteration?

##

For example...

```{bash, eval = F}
qsub -cwd -S /bin/bash script.sh 1
qsub -cwd -S /bin/bash script.sh 2
qsub -cwd -S /bin/bash script.sh 3
```

##

To do this, we need to add a variable to the R script. Let's have a look at the file script-parallel.R.

```{r, eval = F}
args <- commandArgs(trailingOnly=T)
i <- args[1]

Sys.sleep(20)
message(paste("my job number", i, sep=" "))
```

##
Then change your bash script so that it can collect the index from the flag -t

```{bash, eval = F}
#!/bin/bash

Rscript script-parallel.R $SGE_TASK_ID

```

##

Now, you can call your new bash script doing:

```{bash, eval = F}
qsub -t 1-3 -cwd -S /bin/bash script-parallel.sh
```

##

Have a look at the output files to see the results!


# Multicore programming

flag y concepto

# RAM Memory limitations

flag y concepto

# Other parametres

##

Here we will look at the `template.sh`...

##

To call your scripts using this template, you would only need to run:

```{bash, eval = F}
qsub script-parallel.sh
```

The reason is because all the flags and arguments are defined in `template.sh`.

##

Let's have a look at this template:

##

```{bash, eval = F}
##!/bin/bash

###############################
# SGE settings Here
# Basically, if a line starts with "#$", then you can enter any
# qsub command line flags .  See the qsub(1) man page.
# Email address, and options, to whom reports should be sent.
# The -M is for the address, the -m is for when to send email.
# a=abort b=begin e=end s=suspend n=none
##$ -M youremail@domain.com
##$ -m abe

# Redirect the STDOUT and STDERR files to the ~/jobs directory
#$ -o /home/usr123/jobs/
#$ -e /home/usr123/jobs/

# This script, ladies and gentlemen, is in bash
#$ -S /bin/bash

# Do some validation checking, and bail on errors
##$ -w e

# Operate in the current directory
##$ -cwd

# End SGE Settings
###############################
#you can put your scripts here

```

##
